### ISSUE TITLE
Optimize github tests

### ISSUE THREAD

**Issue by ohdearaugustin** [mgit-at/ansible-collection-roles#55]
Only run the molecule test if there was a change in the role.
Currently all molecule tests will run on a push or pullrequest, even thou nothing was changed in the role.

Something like that would be nice:
```
on:
  push:
    paths:
    - 'folder1/**'
  pull_request:
    paths: 
    - 'folder1/**'
```

This will shorten the run time of the tests and lower cost of test.

Maybe also add approval for pull request. So the test are not executed automatically.
