### ISSUE TITLE
Kubernetes Upgrade - Host by Host

### ISSUE THREAD

**Issue by ohdearaugustin** [mgit-at/ansible-collection-roles#74]
The current state of the kubeadm_controlplane will upgrade the `kubernetes_other_control_plane`s simultaneously. This is not really ideal, because if 
you have a 3 node cluster suddenly 2 nodes are tainted and being upgrades.

The initial thought was to fix this with throttle. Unfortunately throttle only works on single tasks. If applied to a `block` also the task in the block will be executed one by one and not the whole block at once.

The current workaround is to add `serial: 1` in the playbook. This will make the roles a bit slower, but ensures only one host is upgraded in parallel. Maybe there is a better solution to that.

**Comment by ohdearaugustin** [comment]
Maybe one approach also could be:
```
- name: Join/reconfigure other control plane nodes
  when:
    - kubernetes_control_plane
    - kubernetes_other_control_plane
  ansible.builtin.include_tasks: other-control-plane-nodes.yml
   delegate_to: "{{ item }}"
   loop: groups['kkubernetes_other_control_plane']
   run_once: true
 ```
